### ISSUE TITLE
Home page feature.

### ISSUE THREAD

**Issue by Vallejoanderson** [Vallejoanderson/ranty-ecommerce#1]
Make each product in the home page be selected if it's already in the cart.

**Comment by Steven-Ha-88** [comment]
Hi Vallejoanderson,

I have a solution for this, may I make a contribution?

**Comment by Vallejoanderson** [comment]
Hello, Steven,

Thanks for jumping in this issue and be open to collaborate with the project. Honestly, I was about to close this issue since I "solved" it, however, I am open to a more elegant and simple solution since mine has still a few incovenients, for example if I switch between topics the counter in the product selected disappear. So, maybe we can keep this issue open if you have more ideas about this issue, anyway you are free to find new bugs or offer new features or ideas to the [project](ranty-ecommerce.netlify.app/) and I will be happy to read more about it,

Regards

**Comment by Steven-Ha-88** [comment]
I have implemented the feature as described: make each product on the home page be selected if the product is in the cart. With my simple solution, the counter doesn't disappear. Should I make a pull request and maybe you can check it out?

**Comment by Vallejoanderson** [comment]
Yes, of course. I will happy to see it :)

**Comment by Vallejoanderson** [comment]
This issue will be closed since it was solved in #3
